### ISSUE TITLE
A Problem about "border-box"

### ISSUE THREAD

**Issue by Copay** [DIYgod/APlayer#20]
Here is a Problem because of Bootstrap and other frontend frames.

It can make the player interface dystopic.

This is an answer to the problem:

```css
.aplayer * {
    box-sizing: content-box;
}
```
