### ISSUE TITLE
Dark mode during night | 暗色模式、黑色模式如何启用

### ISSUE THREAD

**Issue by Matt-wzy** [DIYgod/APlayer#764]
How should I enable dark mode of this player so that users can have a dark interface rather than a white one?
Looking forward to your reply

本项目是否拥有以及如何启用或激活暗色模式/黑色模式/夜间模式？（最好是支持自适应@media  (prefers-color-scheme: dark)，不能自适应的话手动启用方法是什么？）
期望你们的回复。

**Comment by dawnsong** [comment]
我找不到这个黑色模式，索性直接改了css，感兴趣的可以参考：[assets/node_modules/aplayer/dist/xAPlayer.min.css](https://github.com/dawnsong/dawnsong.github.io/raw/refs/heads/main/assets/node_modules/aplayer/dist/xAPlayer.min.css), 效果: https://dawnsong.github.io/

**Comment by Matt-wzy** [comment]
> 我找不到这个黑色模式，索性直接改了css，感兴趣的可以参考：[assets/node_modules/aplayer/dist/xAPlayer.min.css](https://github.com/dawnsong/dawnsong.github.io/raw/refs/heads/main/assets/node_modules/aplayer/dist/xAPlayer.min.css), 效果: https://dawnsong.github.io/

👍

**Comment by TransparentLC** [comment]
@dawnsong 这只有深色模式了……

我自己改的根据 `@media (prefers-color-scheme: dark)` 自动切换的深色模式，基本上是按照反色做的，仅供参考：

![](https://github.com/user-attachments/assets/bfe8f552-b16c-40ee-8dda-1f9331e9e6f0)

<details>

<summary>SCSS</summary>

```scss
@media (prefers-color-scheme: dark) {
    .aplayer {
        background: #333;

        .aplayer-info {
            .aplayer-music {
                .aplayer-title {
                    color: #fff;
                }

                .aplayer-author {
                    color: #aaa;
                }
            }

            .aplayer-controller {
                .aplayer-bar-wrap {
                    .aplayer-bar {
                        background: #666;
                    }
                }

                .aplayer-time {
                    color: #999;

                    .aplayer-icon {
                        path {
                            fill: #aaa;
                        }

                        &:hover {
                            path {
                                fill: #fff;
                            }
                        }
                    }
                }

                .aplayer-volume-wrap {
                    .aplayer-volume-bar-wrap {
                        .aplayer-volume-bar {
                            background: #666;
                        }
                    }
                }
            }
        }

        .aplayer-lrc {
            &:before {
                background: linear-gradient(to bottom, rgba(51,51,51,1) 0%,rgba(51,51,51,0) 100%);
            }

            &:after {
                background: linear-gradient(to bottom, rgba(51,51,51,0) 0%,rgba(51,51,51,0.8) 100%);
            }

            p {
                color: #aaa;
            }
        }

        .aplayer-list {
            ol {
                &::-webkit-scrollbar-thumb {
                    background-color: #222;
                }

                &::-webkit-scrollbar-thumb:hover {
                    background-color: #444;
                }

                li {
                    border-top: 1px solid #171717;

                    &:hover {
                        background: #111;
                    }

                    &.aplayer-list-light {
                        background: #171717;
                    }

                    .aplayer-list-index {
                        color: #aaa;
                    }
                    .aplayer-list-author {
                        color: #aaa;
                    }
                }
            }
        }

        .aplayer-notice {
            background-color: #ccc;
            color: #666;
        }

        .aplayer-miniswitcher {
            background: #1a1a1a;

            .aplayer-icon {
                path {
                    fill: #aaa;
                }

                &:hover {
                    path {
                        fill: #fff;
                    }
                }
            }
        }

        &.aplayer-fixed {
            .aplayer-list {
                border: 1px solid #222;
            }

            .aplayer-body {
                background: #333;
            }

            .aplayer-info {
                border-top: 1px solid #171717;
            }
        }
    }
}
```

</details>

<details>

<summary>CSS</summary>

```css
@media (prefers-color-scheme: dark) {
  .aplayer {
    background: #333;
  }
  .aplayer .aplayer-info .aplayer-music .aplayer-title {
    color: #fff;
  }
  .aplayer .aplayer-info .aplayer-music .aplayer-author {
    color: #aaa;
  }
  .aplayer .aplayer-info .aplayer-controller .aplayer-bar-wrap .aplayer-bar {
    background: #666;
  }
  .aplayer .aplayer-info .aplayer-controller .aplayer-time {
    color: #999;
  }
  .aplayer .aplayer-info .aplayer-controller .aplayer-time .aplayer-icon path {
    fill: #aaa;
  }
  .aplayer .aplayer-info .aplayer-controller .aplayer-time .aplayer-icon:hover path {
    fill: #fff;
  }
  .aplayer .aplayer-info .aplayer-controller .aplayer-volume-wrap .aplayer-volume-bar-wrap .aplayer-volume-bar {
    background: #666;
  }
  .aplayer .aplayer-lrc:before {
    background: linear-gradient(to bottom, rgb(51, 51, 51) 0%, rgba(51, 51, 51, 0) 100%);
  }
  .aplayer .aplayer-lrc:after {
    background: linear-gradient(to bottom, rgba(51, 51, 51, 0) 0%, rgba(51, 51, 51, 0.8) 100%);
  }
  .aplayer .aplayer-lrc p {
    color: #aaa;
  }
  .aplayer .aplayer-list ol::-webkit-scrollbar-thumb {
    background-color: #222;
  }
  .aplayer .aplayer-list ol::-webkit-scrollbar-thumb:hover {
    background-color: #444;
  }
  .aplayer .aplayer-list ol li {
    border-top: 1px solid #171717;
  }
  .aplayer .aplayer-list ol li:hover {
    background: #111;
  }
  .aplayer .aplayer-list ol li.aplayer-list-light {
    background: #171717;
  }
  .aplayer .aplayer-list ol li .aplayer-list-index {
    color: #aaa;
  }
  .aplayer .aplayer-list ol li .aplayer-list-author {
    color: #aaa;
  }
  .aplayer .aplayer-notice {
    background-color: #ccc;
    color: #666;
  }
  .aplayer .aplayer-miniswitcher {
    background: #1a1a1a;
  }
  .aplayer .aplayer-miniswitcher .aplayer-icon path {
    fill: #aaa;
  }
  .aplayer .aplayer-miniswitcher .aplayer-icon:hover path {
    fill: #fff;
  }
  .aplayer.aplayer-fixed .aplayer-list {
    border: 1px solid #222;
  }
  .aplayer.aplayer-fixed .aplayer-body {
    background: #333;
  }
  .aplayer.aplayer-fixed .aplayer-info {
    border-top: 1px solid #171717;
  }
}
```

</details>
